kind: Service
apiVersion: v1
metadata:
  name: docker-api-service
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: docker-api
  type: LoadBalancer
