apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-api-deployment
  labels:
    app: docker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-api
  template:
    metadata:
      labels:
        app: docker-api
    spec:
      containers:
        - name: docker-api
          image: hittten/docker-api
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "localhost"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "1234"
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "1234"
          volumeMounts:
            - name: mongo-db
              mountPath: /data/db
            - name: mongo-db
              mountPath: /data/configdb
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app-deployment
  labels:
    app: docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-app
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
        - name: docker-app
          image: hittten/docker-app:v3.0.0
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: docker-api-service
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: docker-api
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: docker-app-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: docker-app
  type: LoadBalancer
