#Dockefile reference https://docs.docker.com/engine/reference/builder/
FROM node:10

RUN npm install -g npm@v6.12.0 @angular/cli@8.3.9

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY  ./ ./

EXPOSE 4200

CMD ["ng","serve", "--host", "0.0.0.0"]
