version: "3.7"
services:
  app:
    build: .
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: hittten/docker-api
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: 12345
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
